### ISSUE TITLE
老哥这个怎么用

### ISSUE THREAD

**Issue by CaptNo78** [obgnail/chinese-internet-is-dead#1]

**Comment by obgnail** [comment]
看一下知乎 [这篇文章](https://zhuanlan.zhihu.com/p/501854511)

1. 我用的是 uBlacklist，实际上你在 chrome store 搜索【block site】就会有一堆插件。
2. uBlacklist 是开源的，用起来比较放心。如果不知道怎么用，知乎搜索一下关键字就可以找到。
3. 不过 uBlacklist 不支持百度，仅支持 google、Brave、DuckDuckGo、Yahoo 等搜索引擎。
4. 【chinese-internet-is-dead】的所有网址都是我亲手点击进去，发现是垃圾网址后加上去的，已经维护好几年了，所以可以保证 100% 都是垃圾网站。

**Comment by CaptNo78** [comment]
谢谢大佬
