### ISSUE TITLE
为什么抖音被当成垃圾网站了

### ISSUE THREAD

**Issue by yanxu4780** [obgnail/chinese-internet-is-dead#3]
douyin.com
还有 bbs.huaweicloud.com

感觉这两个不用吧？

**Comment by obgnail** [comment]
@yanxu4780 

你好，感谢反馈。

众口难调。

包括阿里云、华为云、XXX云在内的云服务商的 bbs 是内容农场的重灾区。

这里有个很简单的问题：为什么原创作者会去一个云服务商的 bbs 发表内容？

反过来讲，云服务商为什么要建立 bbs？答：SEO，搜索引擎引流。

---

这些网址肯定是有内容的，但是沙里淘金，大部分内容要么是自家的广告，要么是用爬虫技术填充的。

**Comment by by-justin** [comment]
> douyin.com 还有 bbs.huaweicloud.com
> 
> 感觉这两个不用吧？


<img width="1062" alt="image" src="https://github.com/user-attachments/assets/56bc460c-f3ab-4234-a556-ae1ec81e0d6c">
<img width="956" alt="image" src="https://github.com/user-attachments/assets/5664a752-7344-4582-ac22-ffa94d16b8fc">
