### ISSUE TITLE
X (Twitter) 被屏蔽

### ISSUE THREAD

**Issue by chenshaoju** [obgnail/chinese-internet-is-dead#4]
现象：
无法载入推文、热榜(?)等，如下图所示：
![image](https://github.com/user-attachments/assets/097c9f78-c9ee-474c-9ee0-2dc49b04606c)

受影响的规则：
```
/(?<!%)([a-zA-Z0-9]{2,}(%[A-Z0-9]{2}){1,6}[a-zA-Z0-9]{2,}).+?\1/
```

日志信息：
![image](https://github.com/user-attachments/assets/0007e0bf-557b-4f5c-9655-47aa8d438cf5)

**Comment by obgnail** [comment]
@chenshaoju 

你好，感谢反馈。

1. 为了防止误伤，此项目基本不使用正则匹配。

2. 但是前几年搜索引擎留痕技术过于嚣张，一来挡不住，二来他们攻击的是正常网站，无法将网址作为屏蔽特征。无奈只能用这条正则。他们会攻击网站的搜索功能。普通的搜索功能都是使用 GET 请求，他们就伪造请求参数，形成类似如下的 url，以供搜索引擎收录

   ```
   https://website.com/query?搜索引擎留痕工具📌推广网址 XXXX.com📌
   ```

3. 其显著特征就是使用两个 emoji 包裹，而 emoji 会被 url 编码为诸如 `%EF%BF%BD%EF%BF%BD` 的字符串

4. 现在 google、bing 已经改了收录算法，这条规则也就不太重要了，后续我会移除它。

![IMG_2024-10-12_20-26-22 (1)](https://github.com/user-attachments/assets/6b4dd2f9-6728-4ec5-8e89-764ca95d02f5)
