### ISSUE TITLE
介绍一下屏蔽了多少个网站，主要是哪些类别啊

### ISSUE THREAD

**Issue by vicentory** [obgnail/chinese-internet-is-dead#5]
介绍一下屏蔽了多少个网站，主要是哪些类别啊。
还有屏蔽了这么多网站，其实有很多都已经倒闭了，还屏蔽没有意义了吧。

**Comment by obgnail** [comment]
你好。感谢反馈。

1. 很难说具体多少个，有些少部分规则是使用 title 和 regexp 过滤的，他们能过滤一类网址。如果将其视为一个网站，那么一行就是一个网站，共计 4556 个网站。
2. 没有说主要哪些类别，都是我正常上网，遇到一个屏蔽一个所组成的。所以才说是纯手工组成的。
3. 删除倒闭网站问题：搜索引擎一次返回也就二三十条数据，浏览器很擅长做这种过滤操作，并不会有性能问题。实际上有些大的 blocklist 都有几万条。

**Comment by vicentory** [comment]
好的，谢谢
