### ISSUE TITLE
希望添加zlibrary诈骗假冒网站黑名单列表

### ISSUE THREAD

**Issue by BlazeX-Pro** [obgnail/chinese-internet-is-dead#8]
![image](https://github.com/user-attachments/assets/fdc077fc-950b-4e50-89c9-dff86019fc60)
![image](https://github.com/user-attachments/assets/3c1bb442-1c29-4321-b151-7a414c46c2f4)

![image](https://github.com/user-attachments/assets/9892fcb3-3f6a-43b0-8bdc-baf18176a914)
![image](https://github.com/user-attachments/assets/d6c9306b-7481-4ec4-b2ff-cda14cb33a98)

**Comment by obgnail** [comment]
@liehuo0423 

感谢反馈。已经添加，详情请查看 [commit](https://github.com/obgnail/chinese-internet-is-dead/commit/bfe87aba7b3efd4a1ec1a760ff7957313bc8c282)

**Comment by obgnail** [comment]
此 issue 关闭，如有问题，麻烦在下面留言或者另开 issue。

**Comment by obgnail** [comment]
@liehuo0423 

我发现还有其他的假网址，我先搜集一下，之后会发布更完整的屏蔽列表

**Comment by BlazeX-Pro** [comment]
> @liehuo0423 
> 
> 我发现还有其他的假网址，我先搜集一下，之后会发布更完整的屏蔽列表

加油哥
