### ISSUE TITLE
csdn.net 为啥不是 *://*.csdn.net/*

### ISSUE THREAD

**Issue by 1984anonymous** [obgnail/chinese-internet-is-dead#9]
csdn.net 为啥不是 *://*.csdn.net/*

**Comment by obgnail** [comment]
你好，感谢反馈。

因为真的有人在用 CSDN。大范围使用的订阅号不宜太激进。

这就体现了 uBlacklist 插件的好处，订阅和自定义分开，丰俭由人。订阅号给出最低限度的内容，如果您需要，就往自己的屏蔽列表加就行了。

此 issue 关闭，如有问题，麻烦在下面留言或者另开 issue。
